[package]
name = "jokeyrhyme-dotfiles"
description = "read my dotfiles repository and do stuff"
version = "0.1.2"
authors = ["Ron Waldon <jokeyrhyme@gmail.com>"]
documentation = "https://github.com/jokeyrhyme/dotfiles-rs#readme"
homepage = "https://github.com/jokeyrhyme/dotfiles-rs"
repository = "https://github.com/jokeyrhyme/dotfiles-rs"
include = [
  "src/**/*.rs",
  "Cargo.lock",
  "Cargo.toml",
  "LICENSE",
]
license = "MIT"

[dependencies]
clap = "2.30"
