[package]
name = "jokeyrhyme-dotfiles"
description = "read my dotfiles repository and do stuff"
version = "0.32.0"
edition = "2018"
authors = ["Ron Waldon <jokeyrhyme@gmail.com>"]
documentation = "https://github.com/jokeyrhyme/dotfiles-rs#readme"
homepage = "https://github.com/jokeyrhyme/dotfiles-rs"
repository = "https://github.com/jokeyrhyme/dotfiles-rs"
include = [
  "src/**/*.rs",
  "Cargo.lock",
  "Cargo.toml",
  "LICENSE",
]
license = "MIT"

[dependencies]
colored = "1.8"
clap = "2.33"
dirs = "2.0"
Inflector = "0.11.4"
libflate = "0.1.23"
mktemp = "0.4.0"
regex = "1.1"
reqwest = "0.9.17"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
subprocess = "0.1.18"
tar = "0.4.26"
textwrap = "0.11.0"
toml = "0.5.1"
which = "2.0"
zip = "0.5.2"
