[package]
name = "jokeyrhyme-dotfiles"
description = "read my dotfiles repository and do stuff"
version = "0.22.0"
authors = ["Ron Waldon <jokeyrhyme@gmail.com>"]
documentation = "https://github.com/jokeyrhyme/dotfiles-rs#readme"
homepage = "https://github.com/jokeyrhyme/dotfiles-rs"
repository = "https://github.com/jokeyrhyme/dotfiles-rs"
include = [
  "src/**/*.rs",
  "Cargo.lock",
  "Cargo.toml",
  "LICENSE",
]
license = "MIT"

[dependencies]
cabot = "0.2.0"
colored = "1.6"
clap = "2.32"
dirs = "1.0"
Inflector = "0.11.3"
libflate = "0.1.16"
mktemp = "0.3.1"
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tar = "0.4.16"
textwrap = "0.10.0"
toml = "0.4.6"
which = "2.0"
zip = "0.4.2"
